name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  vendor:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Run cargo version --verbose
        run: cargo version --verbose

      - name: Update log to newer commit with same crate version
        run: sed -i s/d1a8306aadb88d56b74c73cdce4ef0153fb549cb/96dbf58ec05e844ec55aa2282f32f612372fbced/ Cargo.toml

      - name: Run cargo vendor
        run: cargo vendor --versioned-dirs > .cargo/config.toml

      - name: Check vendoring of log has changed
        run: test "$(git status --porcelain | grep vendor/log)"

      - name: Display diff
        if: ${{ always() }}
        run: git diff
